version: "3.9"

services:
  web:
    container_name: amnbot
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      # - DATABASE_URL=postgres://myuser:mypassword@db:5432/mydb
      # - SECRET_KEY=cer324vrt4
      - API_KEY=72b98fab79d2d735deb529649533b7b29d978706
      - MODEL=roshanai/roshan
      - TEMPERATURE=0.7
      - BASE_URL=https://llm.roshan-ai.ir/v1



