version: "3.9"

services:
  web:
    container_name: amnbot
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      # - DATABASE_URL=postgres://myuser:mypassword@db:5432/mydb
      # - SECRET_KEY=cer324vrt4
      - API_KEY=aa-5fb263f5TC0jugOSBsc6cHuQMZLUhoaU0ndRiVJUsd30dOxN
      - MODEL=qwen3-235b-a22b
      - TEMPERATURE=0.2
      - BASE_URL=https://api.avalai.ir/v1



